# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbidity_value', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='Date accesed')),
            ],
        ),
    ]
